// src/compile/bundle.ts — inline a compiled program + the whole JS runtime into ONE
// self-contained, dependency-free JavaScript file. Used by
// `sprout build --standalone` to make a program that needs no other files.
//
// The runtime is a handful of small modules (values/errors/explore/builtins/
// jsruntime). We strip their TypeScript types with Node's own built-in stripper
// (zero dependencies) and rewrite their ESM import/export into a tiny require()
// registry, then append the compiled program. The result runs as plain CJS.

import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { stripTypeScriptTypes } from "node:module";

// Dependency order doesn't matter — the registry loads lazily on first require.
// name -> path relative to this file (src/compile/). The runtime modules live in
// a few folders now; we read each from its real home and key them by basename in
// the bundle's tiny require() registry.
const RUNTIME_MODULES: Record<string, string> = {
  values: "../interp/values.ts",
  errors: "../lang/errors.ts",
  explore: "../interp/explore.ts",
  builtins: "../interp/builtins.ts",
  jsruntime: "./jsruntime.ts",
};

// Turn one runtime .ts module into a CJS factory body: strip types, then rewrite
// its ESM `import`/`export` to use our __req() registry. Returns the body plus an
// Object.assign that publishes everything the module exported.
function moduleBody(name: string): string {
  const srcPath = fileURLToPath(new URL(RUNTIME_MODULES[name], import.meta.url));
  // stripTypeScriptTypes is experimental and prints a warning — quiet it.
  const realEmitWarning = process.emitWarning;
  process.emitWarning = () => {};
  let js: string;
  try { js = stripTypeScriptTypes(readFileSync(srcPath, "utf8")); }
  finally { process.emitWarning = realEmitWarning; }
  const exported: string[] = [];
  js = js
    // import { a, b } from "..."  ->  registry __req for our modules, real
    // require() for Node built-ins like "node:fs".
    // Relative imports point at runtime siblings — key them by basename so a
    // cross-folder path like "../interp/values.ts" maps to the registry's "./values.ts".
    .replace(/import\s*\{([^}]*)\}\s*from\s*["']([^"']+)["'];?/g, (_m, names, from) =>
      from.startsWith(".") ? `const {${names}} = __req(${JSON.stringify("./" + from.split("/").pop())});` : `const {${names}} = require(${JSON.stringify(from)});`)
    // export { a, b }  (re-export of in-scope names) -> just record them
    .replace(/export\s*\{([^}]*)\}\s*;?/g, (_m, names: string) => { for (const n of names.split(",")) { const t = n.trim(); if (t) exported.push(t); } return ""; })
    // export function/class NAME -> function/class NAME
    .replace(/export\s+(function|class)\s+([A-Za-z0-9_$]+)/g, (_m, kw, n) => { exported.push(n); return `${kw} ${n}`; })
    // export const/let/var NAME -> const/let/var NAME
    .replace(/export\s+(const|let|var)\s+([A-Za-z0-9_$]+)/g, (_m, kw, n) => { exported.push(n); return `${kw} ${n}`; });
  return js + `\n;Object.assign(exports, { ${[...new Set(exported)].join(", ")} });\n`;
}

// `programJs` is compile()'s output, compiled with runtimeUrl = "@runtime".
export function bundleStandalone(programJs: string): string {
  const out: string[] = [];
  out.push("// A self-contained Sprout program — generated by `sprout build --standalone`.");
  out.push("'use strict';");
  out.push("const __M = {};");
  out.push("function __req(id){ const m = __M[id]; if(!m) throw new Error('missing module '+id); if(m.e) return m.e; m.e = {}; m.f(m.e); return m.e; }");
  for (const name of Object.keys(RUNTIME_MODULES)) {
    out.push(`__M[${JSON.stringify("./" + name + ".ts")}] = { f: function(exports){\n${moduleBody(name)}\n} };`);
  }
  // The compiled program imports the runtime from "@runtime"; point it at our registry.
  const prog = programJs.replace(/import\s*\{([^}]*)\}\s*from\s*["']@runtime["'];?/, (_m, names) => `const {${names}} = __req("./jsruntime.ts");`);
  out.push(prog);
  return out.join("\n") + "\n";
}
